export const contentText: string
export const date: string
export const description: string
export const head: string
export const location: string
export const point: string
export const points: string
export const techStack: string
export const techStackItem: string
export const title: string
export const totalTime: string
